// Fallback dataset used whenever the external APIs are unavailable, return
// empty/null responses, or no API keys are configured yet. This guarantees the
// UI never breaks or shows frozen/zeroed data.
import type { Match } from './types';

const H = {
  superbet: { house: 'Superbet', logo: '🟡' },
  betano: { house: 'Betano', logo: '🟠' },
  bet365: { house: 'Bet365', logo: '🟢' },
  stake: { house: 'Stake', logo: '🔵' },
  sportingbet: { house: 'Sportingbet', logo: '⚫' },
  kto: { house: 'KTO', logo: '🟣' },
  betfair: { house: 'Betfair', logo: '🟡' },
  pixbet: { house: 'Pixbet', logo: '🟢' },
  estrelabet: { house: 'Estrela Bet', logo: '⭐' },
  novibet: { house: 'Novibet', logo: '🔴' },
};

export const fallbackMatches: Match[] = [
  {
    id: 1,
    league: 'Champions League',
    leagueIcon: '🏆',
    homeTeam: { name: 'Real Madrid', shortName: 'RMA', logo: 'https://media.api-sports.io/football/teams/541.png' },
    awayTeam: { name: 'Manchester City', shortName: 'MCI', logo: 'https://media.api-sports.io/football/teams/50.png' },
    homeProb: 58,
    drawProb: 18,
    awayProb: 24,
    homeOdd: 1.72,
    drawOdd: 3.8,
    awayOdd: 4.5,
    valueBet: 'Real Madrid (Vitoria)',
    valueBetOdd: 2.1,
    valueBetHouse: 'Superbet',
    valueBetAdvantage: 'R$ 0,25 acima das outras casas',
    kickoff: '16:00',
    status: 'upcoming',
    expectedGoals: 2.8,
    oddsComparison: [
      { ...H.superbet, homeOdd: 2.1, drawOdd: 3.9, awayOdd: 4.6, isBest: true, bonus: 'Freebet R$20' },
      { ...H.betano, homeOdd: 1.85, drawOdd: 3.8, awayOdd: 4.5, isBest: false },
      { ...H.bet365, homeOdd: 1.8, drawOdd: 3.85, awayOdd: 4.55, isBest: false },
      { ...H.betfair, homeOdd: 1.88, drawOdd: 3.95, awayOdd: 4.65, isBest: false },
      { ...H.stake, homeOdd: 1.78, drawOdd: 3.75, awayOdd: 4.45, isBest: false },
    ],
  },
  {
    id: 2,
    league: 'Brasileirao Serie A',
    leagueIcon: '🇧🇷',
    homeTeam: { name: 'Flamengo', shortName: 'FLA', logo: 'https://media.api-sports.io/football/teams/127.png' },
    awayTeam: { name: 'Palmeiras', shortName: 'PAL', logo: 'https://media.api-sports.io/football/teams/121.png' },
    homeProb: 45,
    drawProb: 28,
    awayProb: 27,
    homeOdd: 2.2,
    drawOdd: 3.25,
    awayOdd: 3.4,
    valueBet: 'Empate',
    valueBetOdd: 3.6,
    valueBetHouse: 'Betano',
    valueBetAdvantage: 'R$ 0,35 acima da media',
    kickoff: '21:30',
    status: 'today',
    expectedGoals: 2.3,
    oddsComparison: [
      { ...H.betano, homeOdd: 2.25, drawOdd: 3.6, awayOdd: 3.45, isBest: true, bonus: 'Aposta Gratis R$50' },
      { ...H.superbet, homeOdd: 2.2, drawOdd: 3.35, awayOdd: 3.4, isBest: false },
      { ...H.bet365, homeOdd: 2.18, drawOdd: 3.3, awayOdd: 3.38, isBest: false },
      { ...H.stake, homeOdd: 2.15, drawOdd: 3.25, awayOdd: 3.35, isBest: false },
      { ...H.pixbet, homeOdd: 2.2, drawOdd: 3.2, awayOdd: 3.3, isBest: false },
    ],
  },
  {
    id: 3,
    league: 'Premier League',
    leagueIcon: '🏴',
    homeTeam: { name: 'Liverpool', shortName: 'LIV', logo: 'https://media.api-sports.io/football/teams/40.png' },
    awayTeam: { name: 'Chelsea', shortName: 'CHE', logo: 'https://media.api-sports.io/football/teams/49.png' },
    homeProb: 52,
    drawProb: 26,
    awayProb: 22,
    homeOdd: 1.95,
    drawOdd: 3.5,
    awayOdd: 3.9,
    valueBet: null,
    valueBetOdd: null,
    valueBetHouse: '',
    valueBetAdvantage: '',
    kickoff: '13:30',
    status: 'live',
    minute: 67,
    homeScore: 2,
    awayScore: 1,
    expectedGoals: 3.1,
    oddsComparison: [
      { ...H.bet365, homeOdd: 1.95, drawOdd: 3.5, awayOdd: 3.9, isBest: true },
      { ...H.betano, homeOdd: 1.92, drawOdd: 3.45, awayOdd: 3.85, isBest: false },
      { ...H.superbet, homeOdd: 1.9, drawOdd: 3.48, awayOdd: 3.88, isBest: false },
      { ...H.betfair, homeOdd: 1.97, drawOdd: 3.55, awayOdd: 3.95, isBest: false },
      { ...H.stake, homeOdd: 1.88, drawOdd: 3.4, awayOdd: 3.8, isBest: false },
    ],
  },
];
